/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Personnel;
import java.awt.*;
/**
 *
 * @author Jordan
 */
public class Fenetre extends javax.swing.JFrame {

    /**
     * Creates new form Fenetre
     */
    private Conteneur<String,Personnel> cont;
    private int total;
    private enum TypePersonnel{EMPLOYE, COMMERCIAL, DIRECTEUR};
    private TypePersonnel typePersonnel;
    private enum ModeCourant{AFFICHAGE,SAISIE, RECHERCHE};
    private ModeCourant modeCourant;
    
    public Fenetre() {
        initComponents();
        typePersonnel = TypePersonnel.EMPLOYE;
        cont= new Conteneur<String, Personnel>();
        total=0;
    }
    
    private void modeaffichage(){
        modeCourant= ModeCourant.AFFICHAGE;
        
    }
    
    private void effacer(){
        /**
         * Mettre tout les champs de texte à blanc chaine ""
         */
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TypesEmployés = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        p_infogen = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_tel = new javax.swing.JTextField();
        tf_nom = new javax.swing.JTextField();
        tf_mat = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        p_typeemp = new javax.swing.JPanel();
        rb_employe = new javax.swing.JRadioButton();
        rb_commercial = new javax.swing.JRadioButton();
        rb_directeur = new javax.swing.JRadioButton();
        p_calculrem = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tf_taux = new javax.swing.JTextField();
        tf_nbh = new javax.swing.JTextField();
        tf_indem = new javax.swing.JTextField();
        tf_ventes = new javax.swing.JTextField();
        tf_pour = new javax.swing.JTextField();
        tf_mb = new javax.swing.JTextField();
        p_gestcont = new javax.swing.JPanel();
        bt_chercher = new javax.swing.JButton();
        bt_supprimer = new javax.swing.JButton();
        bt_creer = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        p_nav = new javax.swing.JPanel();
        bt_debut = new javax.swing.JButton();
        bt_prec = new javax.swing.JButton();
        bt_fin = new javax.swing.JButton();
        bt_suiv = new javax.swing.JButton();
        m_menubar = new javax.swing.JMenuBar();
        m_menufile = new javax.swing.JMenu();
        mi_new = new javax.swing.JMenuItem();
        mi_load = new javax.swing.JMenuItem();
        mi_save = new javax.swing.JMenuItem();
        m_menuhelp = new javax.swing.JMenu();
        mi_about = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Informations générales"); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Personnel/logo1.gif"))); // NOI18N

        p_infogen.setBorder(javax.swing.BorderFactory.createTitledBorder("Informations générales"));
        p_infogen.setToolTipText("Informations génrérales");
        p_infogen.setName("Informations générales"); // NOI18N

        jLabel5.setText("Matricule");

        jLabel4.setText("Tel");

        jLabel3.setText("Nom");

        tf_tel.setToolTipText("");
        tf_tel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_telActionPerformed(evt);
            }
        });

        tf_mat.setToolTipText("Bonjour tu veux des cookies?");

        javax.swing.GroupLayout p_infogenLayout = new javax.swing.GroupLayout(p_infogen);
        p_infogen.setLayout(p_infogenLayout);
        p_infogenLayout.setHorizontalGroup(
            p_infogenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_infogenLayout.createSequentialGroup()
                .addGroup(p_infogenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(p_infogenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_infogenLayout.createSequentialGroup()
                        .addComponent(tf_tel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(tf_mat, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))
                    .addGroup(p_infogenLayout.createSequentialGroup()
                        .addComponent(tf_nom)
                        .addContainerGap())))
        );
        p_infogenLayout.setVerticalGroup(
            p_infogenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_infogenLayout.createSequentialGroup()
                .addGroup(p_infogenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(p_infogenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(tf_tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_mat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Personnel/logo2.gif"))); // NOI18N

        p_typeemp.setBorder(javax.swing.BorderFactory.createTitledBorder("Type d'employés"));

        TypesEmployés.add(rb_employe);
        rb_employe.setText("Employé");

        TypesEmployés.add(rb_commercial);
        rb_commercial.setText("Commercial");

        TypesEmployés.add(rb_directeur);
        rb_directeur.setText("Directeur");

        javax.swing.GroupLayout p_typeempLayout = new javax.swing.GroupLayout(p_typeemp);
        p_typeemp.setLayout(p_typeempLayout);
        p_typeempLayout.setHorizontalGroup(
            p_typeempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_typeempLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rb_employe)
                .addGap(18, 18, 18)
                .addComponent(rb_commercial)
                .addGap(18, 18, 18)
                .addComponent(rb_directeur)
                .addGap(140, 140, 140))
        );
        p_typeempLayout.setVerticalGroup(
            p_typeempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_typeempLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(p_typeempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_directeur)
                    .addComponent(rb_commercial)
                    .addComponent(rb_employe))
                .addGap(57, 57, 57))
        );

        p_calculrem.setBorder(javax.swing.BorderFactory.createTitledBorder("Informations pour le calcul de la rémunération"));

        jLabel7.setText("Taux Horraire");

        jLabel8.setText("Nombres d'heures");

        jLabel9.setText("Indemnités");

        jLabel10.setText("Ventes");

        jLabel11.setText("Pourcentage");

        jLabel12.setText("Montant Brut");

        javax.swing.GroupLayout p_calculremLayout = new javax.swing.GroupLayout(p_calculrem);
        p_calculrem.setLayout(p_calculremLayout);
        p_calculremLayout.setHorizontalGroup(
            p_calculremLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_calculremLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_calculremLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(p_calculremLayout.createSequentialGroup()
                        .addGroup(p_calculremLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(p_calculremLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(29, 29, 29)
                                .addComponent(tf_taux, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(p_calculremLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(p_calculremLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_nbh)
                                    .addComponent(tf_indem))))
                        .addGap(31, 31, 31)
                        .addGroup(p_calculremLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(p_calculremLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_ventes, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_pour, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(p_calculremLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(tf_mb, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        p_calculremLayout.setVerticalGroup(
            p_calculremLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_calculremLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_calculremLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10)
                    .addComponent(tf_taux, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_ventes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p_calculremLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11)
                    .addComponent(tf_nbh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_pour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p_calculremLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tf_mb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(tf_indem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        p_gestcont.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestion du conteneur"));

        bt_chercher.setText("Chercher");
        bt_chercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_chercherActionPerformed(evt);
            }
        });

        bt_supprimer.setText("Supprimer");

        bt_creer.setText("Creer");

        jLabel13.setText("Nombre d'objets présents dans le conteneur :");

        javax.swing.GroupLayout p_gestcontLayout = new javax.swing.GroupLayout(p_gestcont);
        p_gestcont.setLayout(p_gestcontLayout);
        p_gestcontLayout.setHorizontalGroup(
            p_gestcontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_gestcontLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(p_gestcontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_gestcontLayout.createSequentialGroup()
                        .addComponent(bt_chercher)
                        .addGap(118, 118, 118)
                        .addComponent(bt_supprimer))
                    .addGroup(p_gestcontLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel13)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_creer)
                .addGap(60, 60, 60))
        );
        p_gestcontLayout.setVerticalGroup(
            p_gestcontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_gestcontLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_gestcontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_chercher)
                    .addComponent(bt_supprimer)
                    .addComponent(bt_creer))
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        p_nav.setBorder(javax.swing.BorderFactory.createTitledBorder("Navigation dans le conteneur"));

        bt_debut.setText("Début");

        bt_prec.setText("<<");

        bt_fin.setText("Fin");

        bt_suiv.setText(">>");
        bt_suiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_suivActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_navLayout = new javax.swing.GroupLayout(p_nav);
        p_nav.setLayout(p_navLayout);
        p_navLayout.setHorizontalGroup(
            p_navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_navLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(bt_debut)
                .addGap(77, 77, 77)
                .addComponent(bt_prec)
                .addGap(86, 86, 86)
                .addComponent(bt_suiv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_fin)
                .addGap(47, 47, 47))
        );
        p_navLayout.setVerticalGroup(
            p_navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_navLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_debut)
                    .addComponent(bt_prec)
                    .addComponent(bt_fin)
                    .addComponent(bt_suiv))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        m_menufile.setText("File");

        mi_new.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        mi_new.setText("Nouveau...");
        mi_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_newActionPerformed(evt);
            }
        });
        m_menufile.add(mi_new);

        mi_load.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK));
        mi_load.setText("Charger...");
        mi_load.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_loadActionPerformed(evt);
            }
        });
        m_menufile.add(mi_load);

        mi_save.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        mi_save.setText("Sauvegarder...");
        mi_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_saveActionPerformed(evt);
            }
        });
        m_menufile.add(mi_save);

        m_menubar.add(m_menufile);

        m_menuhelp.setText("?");

        mi_about.setText("A propos");
        mi_about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_aboutActionPerformed(evt);
            }
        });
        m_menuhelp.add(mi_about);

        m_menubar.add(m_menuhelp);

        setJMenuBar(m_menubar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addComponent(p_infogen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p_typeemp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p_calculrem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p_gestcont, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p_nav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addComponent(p_infogen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p_typeemp, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p_calculrem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p_gestcont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p_nav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mi_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_newActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mi_newActionPerformed

    private void mi_loadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_loadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mi_loadActionPerformed

    private void mi_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_saveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mi_saveActionPerformed

    private void mi_aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_aboutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mi_aboutActionPerformed

    private void tf_telActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_telActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_telActionPerformed

    private void bt_suivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_suivActionPerformed
        // TODO add your handling code here:
        cont.suivant();
        
    }//GEN-LAST:event_bt_suivActionPerformed

    private void bt_chercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_chercherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_chercherActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fenetre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup TypesEmployés;
    private javax.swing.JButton bt_chercher;
    private javax.swing.JButton bt_creer;
    private javax.swing.JButton bt_debut;
    private javax.swing.JButton bt_fin;
    private javax.swing.JButton bt_prec;
    private javax.swing.JButton bt_suiv;
    private javax.swing.JButton bt_supprimer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar m_menubar;
    private javax.swing.JMenu m_menufile;
    private javax.swing.JMenu m_menuhelp;
    private javax.swing.JMenuItem mi_about;
    private javax.swing.JMenuItem mi_load;
    private javax.swing.JMenuItem mi_new;
    private javax.swing.JMenuItem mi_save;
    private javax.swing.JPanel p_calculrem;
    private javax.swing.JPanel p_gestcont;
    private javax.swing.JPanel p_infogen;
    private javax.swing.JPanel p_nav;
    private javax.swing.JPanel p_typeemp;
    private javax.swing.JRadioButton rb_commercial;
    private javax.swing.JRadioButton rb_directeur;
    private javax.swing.JRadioButton rb_employe;
    private javax.swing.JTextField tf_indem;
    private javax.swing.JTextField tf_mat;
    private javax.swing.JTextField tf_mb;
    private javax.swing.JTextField tf_nbh;
    private javax.swing.JTextField tf_nom;
    private javax.swing.JTextField tf_pour;
    private javax.swing.JTextField tf_taux;
    private javax.swing.JTextField tf_tel;
    private javax.swing.JTextField tf_ventes;
    // End of variables declaration//GEN-END:variables
}
